server:
  port: 8081

## http://localhost:8081/h2-console
spring:
  h2:
    console:
      enabled: true
  application:
    name: order-service

eureka:
  client:
    register-with-eureka: true # With false, it is not discoverable from eureka
    fetch-registry: true # With false, it is not discoverable from eureka
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost